/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './app/__root';
import { Route as TermsOfServiceRouteImport } from './app/terms-of-service';
import { Route as PrivacyPolicyRouteImport } from './app/privacy-policy';
import { Route as AboutRouteImport } from './app/about';
import { Route as DashboardRouteRouteImport } from './app/dashboard/route';
import { Route as IndexRouteImport } from './app/index';
import { Route as DashboardIndexRouteImport } from './app/dashboard/index';
import { Route as AuthIndexRouteImport } from './app/auth/index';
import { Route as DashboardWorkspacesRouteImport } from './app/dashboard/workspaces';
import { Route as DashboardUsersRouteImport } from './app/dashboard/users';
import { Route as DashboardReactQueryRouteImport } from './app/dashboard/react-query';
import { Route as DashboardProfileRouteImport } from './app/dashboard/profile';
import { Route as DashboardProductRouteImport } from './app/dashboard/product';
import { Route as DashboardOverviewRouteImport } from './app/dashboard/overview';
import { Route as DashboardNotificationsRouteImport } from './app/dashboard/notifications';
import { Route as DashboardKanbanRouteImport } from './app/dashboard/kanban';
import { Route as DashboardExclusiveRouteImport } from './app/dashboard/exclusive';
import { Route as DashboardChatRouteImport } from './app/dashboard/chat';
import { Route as DashboardBillingRouteImport } from './app/dashboard/billing';
import { Route as AuthSignUpRouteImport } from './app/auth/sign-up';
import { Route as AuthSignInRouteImport } from './app/auth/sign-in';
import { Route as ApiUsersRouteImport } from './app/api/users';
import { Route as ApiProductsRouteImport } from './app/api/products';
import { Route as DashboardProductIndexRouteImport } from './app/dashboard/product/index';
import { Route as DashboardFormsIndexRouteImport } from './app/dashboard/forms/index';
import { Route as DashboardWorkspacesTeamRouteImport } from './app/dashboard/workspaces/team';
import { Route as DashboardProductProductIdRouteImport } from './app/dashboard/product/$productId';
import { Route as DashboardFormsSheetFormRouteImport } from './app/dashboard/forms/sheet-form';
import { Route as DashboardFormsMultiStepRouteImport } from './app/dashboard/forms/multi-step';
import { Route as DashboardFormsBasicRouteImport } from './app/dashboard/forms/basic';
import { Route as DashboardFormsAdvancedRouteImport } from './app/dashboard/forms/advanced';
import { Route as DashboardElementsIconsRouteImport } from './app/dashboard/elements/icons';
import { Route as ApiAuthSplatRouteImport } from './app/api/auth/$';

const TermsOfServiceRoute = TermsOfServiceRouteImport.update({
  id: '/terms-of-service',
  path: '/terms-of-service',
  getParentRoute: () => rootRouteImport
} as any);
const PrivacyPolicyRoute = PrivacyPolicyRouteImport.update({
  id: '/privacy-policy',
  path: '/privacy-policy',
  getParentRoute: () => rootRouteImport
} as any);
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport
} as any);
const DashboardRouteRoute = DashboardRouteRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport
} as any);
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport
} as any);
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRouteRoute
} as any);
const AuthIndexRoute = AuthIndexRouteImport.update({
  id: '/auth/',
  path: '/auth/',
  getParentRoute: () => rootRouteImport
} as any);
const DashboardWorkspacesRoute = DashboardWorkspacesRouteImport.update({
  id: '/workspaces',
  path: '/workspaces',
  getParentRoute: () => DashboardRouteRoute
} as any);
const DashboardUsersRoute = DashboardUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => DashboardRouteRoute
} as any);
const DashboardReactQueryRoute = DashboardReactQueryRouteImport.update({
  id: '/react-query',
  path: '/react-query',
  getParentRoute: () => DashboardRouteRoute
} as any);
const DashboardProfileRoute = DashboardProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => DashboardRouteRoute
} as any);
const DashboardProductRoute = DashboardProductRouteImport.update({
  id: '/product',
  path: '/product',
  getParentRoute: () => DashboardRouteRoute
} as any);
const DashboardOverviewRoute = DashboardOverviewRouteImport.update({
  id: '/overview',
  path: '/overview',
  getParentRoute: () => DashboardRouteRoute
} as any);
const DashboardNotificationsRoute = DashboardNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => DashboardRouteRoute
} as any);
const DashboardKanbanRoute = DashboardKanbanRouteImport.update({
  id: '/kanban',
  path: '/kanban',
  getParentRoute: () => DashboardRouteRoute
} as any);
const DashboardExclusiveRoute = DashboardExclusiveRouteImport.update({
  id: '/exclusive',
  path: '/exclusive',
  getParentRoute: () => DashboardRouteRoute
} as any);
const DashboardChatRoute = DashboardChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => DashboardRouteRoute
} as any);
const DashboardBillingRoute = DashboardBillingRouteImport.update({
  id: '/billing',
  path: '/billing',
  getParentRoute: () => DashboardRouteRoute
} as any);
const AuthSignUpRoute = AuthSignUpRouteImport.update({
  id: '/auth/sign-up',
  path: '/auth/sign-up',
  getParentRoute: () => rootRouteImport
} as any);
const AuthSignInRoute = AuthSignInRouteImport.update({
  id: '/auth/sign-in',
  path: '/auth/sign-in',
  getParentRoute: () => rootRouteImport
} as any);
const ApiUsersRoute = ApiUsersRouteImport.update({
  id: '/api/users',
  path: '/api/users',
  getParentRoute: () => rootRouteImport
} as any);
const ApiProductsRoute = ApiProductsRouteImport.update({
  id: '/api/products',
  path: '/api/products',
  getParentRoute: () => rootRouteImport
} as any);
const DashboardProductIndexRoute = DashboardProductIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardProductRoute
} as any);
const DashboardFormsIndexRoute = DashboardFormsIndexRouteImport.update({
  id: '/forms/',
  path: '/forms/',
  getParentRoute: () => DashboardRouteRoute
} as any);
const DashboardWorkspacesTeamRoute = DashboardWorkspacesTeamRouteImport.update({
  id: '/team',
  path: '/team',
  getParentRoute: () => DashboardWorkspacesRoute
} as any);
const DashboardProductProductIdRoute = DashboardProductProductIdRouteImport.update({
  id: '/$productId',
  path: '/$productId',
  getParentRoute: () => DashboardProductRoute
} as any);
const DashboardFormsSheetFormRoute = DashboardFormsSheetFormRouteImport.update({
  id: '/forms/sheet-form',
  path: '/forms/sheet-form',
  getParentRoute: () => DashboardRouteRoute
} as any);
const DashboardFormsMultiStepRoute = DashboardFormsMultiStepRouteImport.update({
  id: '/forms/multi-step',
  path: '/forms/multi-step',
  getParentRoute: () => DashboardRouteRoute
} as any);
const DashboardFormsBasicRoute = DashboardFormsBasicRouteImport.update({
  id: '/forms/basic',
  path: '/forms/basic',
  getParentRoute: () => DashboardRouteRoute
} as any);
const DashboardFormsAdvancedRoute = DashboardFormsAdvancedRouteImport.update({
  id: '/forms/advanced',
  path: '/forms/advanced',
  getParentRoute: () => DashboardRouteRoute
} as any);
const DashboardElementsIconsRoute = DashboardElementsIconsRouteImport.update({
  id: '/elements/icons',
  path: '/elements/icons',
  getParentRoute: () => DashboardRouteRoute
} as any);
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport
} as any);

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute;
  '/dashboard': typeof DashboardRouteRouteWithChildren;
  '/about': typeof AboutRoute;
  '/privacy-policy': typeof PrivacyPolicyRoute;
  '/terms-of-service': typeof TermsOfServiceRoute;
  '/api/products': typeof ApiProductsRoute;
  '/api/users': typeof ApiUsersRoute;
  '/auth/sign-in': typeof AuthSignInRoute;
  '/auth/sign-up': typeof AuthSignUpRoute;
  '/dashboard/billing': typeof DashboardBillingRoute;
  '/dashboard/chat': typeof DashboardChatRoute;
  '/dashboard/exclusive': typeof DashboardExclusiveRoute;
  '/dashboard/kanban': typeof DashboardKanbanRoute;
  '/dashboard/notifications': typeof DashboardNotificationsRoute;
  '/dashboard/overview': typeof DashboardOverviewRoute;
  '/dashboard/product': typeof DashboardProductRouteWithChildren;
  '/dashboard/profile': typeof DashboardProfileRoute;
  '/dashboard/react-query': typeof DashboardReactQueryRoute;
  '/dashboard/users': typeof DashboardUsersRoute;
  '/dashboard/workspaces': typeof DashboardWorkspacesRouteWithChildren;
  '/auth/': typeof AuthIndexRoute;
  '/dashboard/': typeof DashboardIndexRoute;
  '/api/auth/$': typeof ApiAuthSplatRoute;
  '/dashboard/elements/icons': typeof DashboardElementsIconsRoute;
  '/dashboard/forms/advanced': typeof DashboardFormsAdvancedRoute;
  '/dashboard/forms/basic': typeof DashboardFormsBasicRoute;
  '/dashboard/forms/multi-step': typeof DashboardFormsMultiStepRoute;
  '/dashboard/forms/sheet-form': typeof DashboardFormsSheetFormRoute;
  '/dashboard/product/$productId': typeof DashboardProductProductIdRoute;
  '/dashboard/workspaces/team': typeof DashboardWorkspacesTeamRoute;
  '/dashboard/forms/': typeof DashboardFormsIndexRoute;
  '/dashboard/product/': typeof DashboardProductIndexRoute;
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute;
  '/about': typeof AboutRoute;
  '/privacy-policy': typeof PrivacyPolicyRoute;
  '/terms-of-service': typeof TermsOfServiceRoute;
  '/api/products': typeof ApiProductsRoute;
  '/api/users': typeof ApiUsersRoute;
  '/auth/sign-in': typeof AuthSignInRoute;
  '/auth/sign-up': typeof AuthSignUpRoute;
  '/dashboard/billing': typeof DashboardBillingRoute;
  '/dashboard/chat': typeof DashboardChatRoute;
  '/dashboard/exclusive': typeof DashboardExclusiveRoute;
  '/dashboard/kanban': typeof DashboardKanbanRoute;
  '/dashboard/notifications': typeof DashboardNotificationsRoute;
  '/dashboard/overview': typeof DashboardOverviewRoute;
  '/dashboard/profile': typeof DashboardProfileRoute;
  '/dashboard/react-query': typeof DashboardReactQueryRoute;
  '/dashboard/users': typeof DashboardUsersRoute;
  '/dashboard/workspaces': typeof DashboardWorkspacesRouteWithChildren;
  '/auth': typeof AuthIndexRoute;
  '/dashboard': typeof DashboardIndexRoute;
  '/api/auth/$': typeof ApiAuthSplatRoute;
  '/dashboard/elements/icons': typeof DashboardElementsIconsRoute;
  '/dashboard/forms/advanced': typeof DashboardFormsAdvancedRoute;
  '/dashboard/forms/basic': typeof DashboardFormsBasicRoute;
  '/dashboard/forms/multi-step': typeof DashboardFormsMultiStepRoute;
  '/dashboard/forms/sheet-form': typeof DashboardFormsSheetFormRoute;
  '/dashboard/product/$productId': typeof DashboardProductProductIdRoute;
  '/dashboard/workspaces/team': typeof DashboardWorkspacesTeamRoute;
  '/dashboard/forms': typeof DashboardFormsIndexRoute;
  '/dashboard/product': typeof DashboardProductIndexRoute;
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport;
  '/': typeof IndexRoute;
  '/dashboard': typeof DashboardRouteRouteWithChildren;
  '/about': typeof AboutRoute;
  '/privacy-policy': typeof PrivacyPolicyRoute;
  '/terms-of-service': typeof TermsOfServiceRoute;
  '/api/products': typeof ApiProductsRoute;
  '/api/users': typeof ApiUsersRoute;
  '/auth/sign-in': typeof AuthSignInRoute;
  '/auth/sign-up': typeof AuthSignUpRoute;
  '/dashboard/billing': typeof DashboardBillingRoute;
  '/dashboard/chat': typeof DashboardChatRoute;
  '/dashboard/exclusive': typeof DashboardExclusiveRoute;
  '/dashboard/kanban': typeof DashboardKanbanRoute;
  '/dashboard/notifications': typeof DashboardNotificationsRoute;
  '/dashboard/overview': typeof DashboardOverviewRoute;
  '/dashboard/product': typeof DashboardProductRouteWithChildren;
  '/dashboard/profile': typeof DashboardProfileRoute;
  '/dashboard/react-query': typeof DashboardReactQueryRoute;
  '/dashboard/users': typeof DashboardUsersRoute;
  '/dashboard/workspaces': typeof DashboardWorkspacesRouteWithChildren;
  '/auth/': typeof AuthIndexRoute;
  '/dashboard/': typeof DashboardIndexRoute;
  '/api/auth/$': typeof ApiAuthSplatRoute;
  '/dashboard/elements/icons': typeof DashboardElementsIconsRoute;
  '/dashboard/forms/advanced': typeof DashboardFormsAdvancedRoute;
  '/dashboard/forms/basic': typeof DashboardFormsBasicRoute;
  '/dashboard/forms/multi-step': typeof DashboardFormsMultiStepRoute;
  '/dashboard/forms/sheet-form': typeof DashboardFormsSheetFormRoute;
  '/dashboard/product/$productId': typeof DashboardProductProductIdRoute;
  '/dashboard/workspaces/team': typeof DashboardWorkspacesTeamRoute;
  '/dashboard/forms/': typeof DashboardFormsIndexRoute;
  '/dashboard/product/': typeof DashboardProductIndexRoute;
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath;
  fullPaths:
    | '/'
    | '/dashboard'
    | '/about'
    | '/privacy-policy'
    | '/terms-of-service'
    | '/api/products'
    | '/api/users'
    | '/auth/sign-in'
    | '/auth/sign-up'
    | '/dashboard/billing'
    | '/dashboard/chat'
    | '/dashboard/exclusive'
    | '/dashboard/kanban'
    | '/dashboard/notifications'
    | '/dashboard/overview'
    | '/dashboard/product'
    | '/dashboard/profile'
    | '/dashboard/react-query'
    | '/dashboard/users'
    | '/dashboard/workspaces'
    | '/auth/'
    | '/dashboard/'
    | '/api/auth/$'
    | '/dashboard/elements/icons'
    | '/dashboard/forms/advanced'
    | '/dashboard/forms/basic'
    | '/dashboard/forms/multi-step'
    | '/dashboard/forms/sheet-form'
    | '/dashboard/product/$productId'
    | '/dashboard/workspaces/team'
    | '/dashboard/forms/'
    | '/dashboard/product/';
  fileRoutesByTo: FileRoutesByTo;
  to:
    | '/'
    | '/about'
    | '/privacy-policy'
    | '/terms-of-service'
    | '/api/products'
    | '/api/users'
    | '/auth/sign-in'
    | '/auth/sign-up'
    | '/dashboard/billing'
    | '/dashboard/chat'
    | '/dashboard/exclusive'
    | '/dashboard/kanban'
    | '/dashboard/notifications'
    | '/dashboard/overview'
    | '/dashboard/profile'
    | '/dashboard/react-query'
    | '/dashboard/users'
    | '/dashboard/workspaces'
    | '/auth'
    | '/dashboard'
    | '/api/auth/$'
    | '/dashboard/elements/icons'
    | '/dashboard/forms/advanced'
    | '/dashboard/forms/basic'
    | '/dashboard/forms/multi-step'
    | '/dashboard/forms/sheet-form'
    | '/dashboard/product/$productId'
    | '/dashboard/workspaces/team'
    | '/dashboard/forms'
    | '/dashboard/product';
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/about'
    | '/privacy-policy'
    | '/terms-of-service'
    | '/api/products'
    | '/api/users'
    | '/auth/sign-in'
    | '/auth/sign-up'
    | '/dashboard/billing'
    | '/dashboard/chat'
    | '/dashboard/exclusive'
    | '/dashboard/kanban'
    | '/dashboard/notifications'
    | '/dashboard/overview'
    | '/dashboard/product'
    | '/dashboard/profile'
    | '/dashboard/react-query'
    | '/dashboard/users'
    | '/dashboard/workspaces'
    | '/auth/'
    | '/dashboard/'
    | '/api/auth/$'
    | '/dashboard/elements/icons'
    | '/dashboard/forms/advanced'
    | '/dashboard/forms/basic'
    | '/dashboard/forms/multi-step'
    | '/dashboard/forms/sheet-form'
    | '/dashboard/product/$productId'
    | '/dashboard/workspaces/team'
    | '/dashboard/forms/'
    | '/dashboard/product/';
  fileRoutesById: FileRoutesById;
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute;
  DashboardRouteRoute: typeof DashboardRouteRouteWithChildren;
  AboutRoute: typeof AboutRoute;
  PrivacyPolicyRoute: typeof PrivacyPolicyRoute;
  TermsOfServiceRoute: typeof TermsOfServiceRoute;
  ApiProductsRoute: typeof ApiProductsRoute;
  ApiUsersRoute: typeof ApiUsersRoute;
  AuthSignInRoute: typeof AuthSignInRoute;
  AuthSignUpRoute: typeof AuthSignUpRoute;
  AuthIndexRoute: typeof AuthIndexRoute;
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute;
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/terms-of-service': {
      id: '/terms-of-service';
      path: '/terms-of-service';
      fullPath: '/terms-of-service';
      preLoaderRoute: typeof TermsOfServiceRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    '/privacy-policy': {
      id: '/privacy-policy';
      path: '/privacy-policy';
      fullPath: '/privacy-policy';
      preLoaderRoute: typeof PrivacyPolicyRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    '/about': {
      id: '/about';
      path: '/about';
      fullPath: '/about';
      preLoaderRoute: typeof AboutRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    '/dashboard': {
      id: '/dashboard';
      path: '/dashboard';
      fullPath: '/dashboard';
      preLoaderRoute: typeof DashboardRouteRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    '/': {
      id: '/';
      path: '/';
      fullPath: '/';
      preLoaderRoute: typeof IndexRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    '/dashboard/': {
      id: '/dashboard/';
      path: '/';
      fullPath: '/dashboard/';
      preLoaderRoute: typeof DashboardIndexRouteImport;
      parentRoute: typeof DashboardRouteRoute;
    };
    '/auth/': {
      id: '/auth/';
      path: '/auth';
      fullPath: '/auth/';
      preLoaderRoute: typeof AuthIndexRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    '/dashboard/workspaces': {
      id: '/dashboard/workspaces';
      path: '/workspaces';
      fullPath: '/dashboard/workspaces';
      preLoaderRoute: typeof DashboardWorkspacesRouteImport;
      parentRoute: typeof DashboardRouteRoute;
    };
    '/dashboard/users': {
      id: '/dashboard/users';
      path: '/users';
      fullPath: '/dashboard/users';
      preLoaderRoute: typeof DashboardUsersRouteImport;
      parentRoute: typeof DashboardRouteRoute;
    };
    '/dashboard/react-query': {
      id: '/dashboard/react-query';
      path: '/react-query';
      fullPath: '/dashboard/react-query';
      preLoaderRoute: typeof DashboardReactQueryRouteImport;
      parentRoute: typeof DashboardRouteRoute;
    };
    '/dashboard/profile': {
      id: '/dashboard/profile';
      path: '/profile';
      fullPath: '/dashboard/profile';
      preLoaderRoute: typeof DashboardProfileRouteImport;
      parentRoute: typeof DashboardRouteRoute;
    };
    '/dashboard/product': {
      id: '/dashboard/product';
      path: '/product';
      fullPath: '/dashboard/product';
      preLoaderRoute: typeof DashboardProductRouteImport;
      parentRoute: typeof DashboardRouteRoute;
    };
    '/dashboard/overview': {
      id: '/dashboard/overview';
      path: '/overview';
      fullPath: '/dashboard/overview';
      preLoaderRoute: typeof DashboardOverviewRouteImport;
      parentRoute: typeof DashboardRouteRoute;
    };
    '/dashboard/notifications': {
      id: '/dashboard/notifications';
      path: '/notifications';
      fullPath: '/dashboard/notifications';
      preLoaderRoute: typeof DashboardNotificationsRouteImport;
      parentRoute: typeof DashboardRouteRoute;
    };
    '/dashboard/kanban': {
      id: '/dashboard/kanban';
      path: '/kanban';
      fullPath: '/dashboard/kanban';
      preLoaderRoute: typeof DashboardKanbanRouteImport;
      parentRoute: typeof DashboardRouteRoute;
    };
    '/dashboard/exclusive': {
      id: '/dashboard/exclusive';
      path: '/exclusive';
      fullPath: '/dashboard/exclusive';
      preLoaderRoute: typeof DashboardExclusiveRouteImport;
      parentRoute: typeof DashboardRouteRoute;
    };
    '/dashboard/chat': {
      id: '/dashboard/chat';
      path: '/chat';
      fullPath: '/dashboard/chat';
      preLoaderRoute: typeof DashboardChatRouteImport;
      parentRoute: typeof DashboardRouteRoute;
    };
    '/dashboard/billing': {
      id: '/dashboard/billing';
      path: '/billing';
      fullPath: '/dashboard/billing';
      preLoaderRoute: typeof DashboardBillingRouteImport;
      parentRoute: typeof DashboardRouteRoute;
    };
    '/auth/sign-up': {
      id: '/auth/sign-up';
      path: '/auth/sign-up';
      fullPath: '/auth/sign-up';
      preLoaderRoute: typeof AuthSignUpRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    '/auth/sign-in': {
      id: '/auth/sign-in';
      path: '/auth/sign-in';
      fullPath: '/auth/sign-in';
      preLoaderRoute: typeof AuthSignInRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    '/api/users': {
      id: '/api/users';
      path: '/api/users';
      fullPath: '/api/users';
      preLoaderRoute: typeof ApiUsersRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    '/api/products': {
      id: '/api/products';
      path: '/api/products';
      fullPath: '/api/products';
      preLoaderRoute: typeof ApiProductsRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    '/dashboard/product/': {
      id: '/dashboard/product/';
      path: '/';
      fullPath: '/dashboard/product/';
      preLoaderRoute: typeof DashboardProductIndexRouteImport;
      parentRoute: typeof DashboardProductRoute;
    };
    '/dashboard/forms/': {
      id: '/dashboard/forms/';
      path: '/forms';
      fullPath: '/dashboard/forms/';
      preLoaderRoute: typeof DashboardFormsIndexRouteImport;
      parentRoute: typeof DashboardRouteRoute;
    };
    '/dashboard/workspaces/team': {
      id: '/dashboard/workspaces/team';
      path: '/team';
      fullPath: '/dashboard/workspaces/team';
      preLoaderRoute: typeof DashboardWorkspacesTeamRouteImport;
      parentRoute: typeof DashboardWorkspacesRoute;
    };
    '/dashboard/product/$productId': {
      id: '/dashboard/product/$productId';
      path: '/$productId';
      fullPath: '/dashboard/product/$productId';
      preLoaderRoute: typeof DashboardProductProductIdRouteImport;
      parentRoute: typeof DashboardProductRoute;
    };
    '/dashboard/forms/sheet-form': {
      id: '/dashboard/forms/sheet-form';
      path: '/forms/sheet-form';
      fullPath: '/dashboard/forms/sheet-form';
      preLoaderRoute: typeof DashboardFormsSheetFormRouteImport;
      parentRoute: typeof DashboardRouteRoute;
    };
    '/dashboard/forms/multi-step': {
      id: '/dashboard/forms/multi-step';
      path: '/forms/multi-step';
      fullPath: '/dashboard/forms/multi-step';
      preLoaderRoute: typeof DashboardFormsMultiStepRouteImport;
      parentRoute: typeof DashboardRouteRoute;
    };
    '/dashboard/forms/basic': {
      id: '/dashboard/forms/basic';
      path: '/forms/basic';
      fullPath: '/dashboard/forms/basic';
      preLoaderRoute: typeof DashboardFormsBasicRouteImport;
      parentRoute: typeof DashboardRouteRoute;
    };
    '/dashboard/forms/advanced': {
      id: '/dashboard/forms/advanced';
      path: '/forms/advanced';
      fullPath: '/dashboard/forms/advanced';
      preLoaderRoute: typeof DashboardFormsAdvancedRouteImport;
      parentRoute: typeof DashboardRouteRoute;
    };
    '/dashboard/elements/icons': {
      id: '/dashboard/elements/icons';
      path: '/elements/icons';
      fullPath: '/dashboard/elements/icons';
      preLoaderRoute: typeof DashboardElementsIconsRouteImport;
      parentRoute: typeof DashboardRouteRoute;
    };
    '/api/auth/$': {
      id: '/api/auth/$';
      path: '/api/auth/$';
      fullPath: '/api/auth/$';
      preLoaderRoute: typeof ApiAuthSplatRouteImport;
      parentRoute: typeof rootRouteImport;
    };
  }
}

interface DashboardProductRouteChildren {
  DashboardProductProductIdRoute: typeof DashboardProductProductIdRoute;
  DashboardProductIndexRoute: typeof DashboardProductIndexRoute;
}

const DashboardProductRouteChildren: DashboardProductRouteChildren = {
  DashboardProductProductIdRoute: DashboardProductProductIdRoute,
  DashboardProductIndexRoute: DashboardProductIndexRoute
};

const DashboardProductRouteWithChildren = DashboardProductRoute._addFileChildren(
  DashboardProductRouteChildren
);

interface DashboardWorkspacesRouteChildren {
  DashboardWorkspacesTeamRoute: typeof DashboardWorkspacesTeamRoute;
}

const DashboardWorkspacesRouteChildren: DashboardWorkspacesRouteChildren = {
  DashboardWorkspacesTeamRoute: DashboardWorkspacesTeamRoute
};

const DashboardWorkspacesRouteWithChildren = DashboardWorkspacesRoute._addFileChildren(
  DashboardWorkspacesRouteChildren
);

interface DashboardRouteRouteChildren {
  DashboardBillingRoute: typeof DashboardBillingRoute;
  DashboardChatRoute: typeof DashboardChatRoute;
  DashboardExclusiveRoute: typeof DashboardExclusiveRoute;
  DashboardKanbanRoute: typeof DashboardKanbanRoute;
  DashboardNotificationsRoute: typeof DashboardNotificationsRoute;
  DashboardOverviewRoute: typeof DashboardOverviewRoute;
  DashboardProductRoute: typeof DashboardProductRouteWithChildren;
  DashboardProfileRoute: typeof DashboardProfileRoute;
  DashboardReactQueryRoute: typeof DashboardReactQueryRoute;
  DashboardUsersRoute: typeof DashboardUsersRoute;
  DashboardWorkspacesRoute: typeof DashboardWorkspacesRouteWithChildren;
  DashboardIndexRoute: typeof DashboardIndexRoute;
  DashboardElementsIconsRoute: typeof DashboardElementsIconsRoute;
  DashboardFormsAdvancedRoute: typeof DashboardFormsAdvancedRoute;
  DashboardFormsBasicRoute: typeof DashboardFormsBasicRoute;
  DashboardFormsMultiStepRoute: typeof DashboardFormsMultiStepRoute;
  DashboardFormsSheetFormRoute: typeof DashboardFormsSheetFormRoute;
  DashboardFormsIndexRoute: typeof DashboardFormsIndexRoute;
}

const DashboardRouteRouteChildren: DashboardRouteRouteChildren = {
  DashboardBillingRoute: DashboardBillingRoute,
  DashboardChatRoute: DashboardChatRoute,
  DashboardExclusiveRoute: DashboardExclusiveRoute,
  DashboardKanbanRoute: DashboardKanbanRoute,
  DashboardNotificationsRoute: DashboardNotificationsRoute,
  DashboardOverviewRoute: DashboardOverviewRoute,
  DashboardProductRoute: DashboardProductRouteWithChildren,
  DashboardProfileRoute: DashboardProfileRoute,
  DashboardReactQueryRoute: DashboardReactQueryRoute,
  DashboardUsersRoute: DashboardUsersRoute,
  DashboardWorkspacesRoute: DashboardWorkspacesRouteWithChildren,
  DashboardIndexRoute: DashboardIndexRoute,
  DashboardElementsIconsRoute: DashboardElementsIconsRoute,
  DashboardFormsAdvancedRoute: DashboardFormsAdvancedRoute,
  DashboardFormsBasicRoute: DashboardFormsBasicRoute,
  DashboardFormsMultiStepRoute: DashboardFormsMultiStepRoute,
  DashboardFormsSheetFormRoute: DashboardFormsSheetFormRoute,
  DashboardFormsIndexRoute: DashboardFormsIndexRoute
};

const DashboardRouteRouteWithChildren = DashboardRouteRoute._addFileChildren(
  DashboardRouteRouteChildren
);

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRouteRoute: DashboardRouteRouteWithChildren,
  AboutRoute: AboutRoute,
  PrivacyPolicyRoute: PrivacyPolicyRoute,
  TermsOfServiceRoute: TermsOfServiceRoute,
  ApiProductsRoute: ApiProductsRoute,
  ApiUsersRoute: ApiUsersRoute,
  AuthSignInRoute: AuthSignInRoute,
  AuthSignUpRoute: AuthSignUpRoute,
  AuthIndexRoute: AuthIndexRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute
};
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>();

import type { getRouter } from './router.tsx';
import type { startInstance } from './start.ts';
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true;
    router: Awaited<ReturnType<typeof getRouter>>;
    config: Awaited<ReturnType<typeof startInstance.getOptions>>;
  }
}
